version: '3.8'

services:
  wiremock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./mappings:/home/wiremock/mappings
    command: ["--port", "8082", "--root-dir", "/home/wiremock"]
